### ISSUE TITLE
Feature 1 Dynamic Content Loading

### ISSUE THREAD

**Issue by jfues** [victordevlin/Team4Sprint1#1]
Product Backlog
### Task
- [ ] Task 1 Modify index.html to include an empty content container #1
- [ ] Task 2 Update myscripts.js to load content dynamically without full page reloads # 2 
- [ ] Task 3 Update directory structure to include content directory for articles
