### ISSUE TITLE
Sprint2 Backlog Feature 4 - Content Articles

### ISSUE THREAD

**Issue by victordevlin** [victordevlin/Team4Sprint1#8]
### Task

- [x] Task 1: Climb the Mountain
- [x] Task 2: Wander The Forest
- [x] Task 3: See The Falls
- [x] Task 4: Ride the Ferry
- [x] Task 5: Walk Around the Lake
- [x] Task 6: Read in the Park
